apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pody
  name: pody
spec:
  containers:
  - image: nginx
    name: pody
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
